clear all; close all; 
% Initialisation
init; clc;
%{
%% 1. Data loading/generation

% Select dataset among {'Toy_Gaussian', 'Toy_Spiral', 'Toy_Circle', 'Caltech'}
[data_train, data_test] = getData('Toy_Spiral');

%%%%%%%%%%%%%
% check the training data
    % data_train(:,1:2) : [num_data x dim] Training 2D vectors
    % data_train(:,3) : [num_data x 1] Labels of training data, {1,2,3}
    
plot_toydata(data_train);

% check the test data
% data_test(:,1:2) : [num_data x dim] Testing 2D vectors, 2D points in the
% uniform dense grid within the range of [-1.5, 1.5]
% data_train(:,3) : N/A
figure;
scatter(data_test(:,1),data_test(:,2),'.b');

%%%%%%%%%%%%%%%%%%%%%%

%% 2. Random Forest Training
%% 2.1 Bagging: Creating subsets of training data

[N,D] = size(data_train);
frac = 1; % Bootstrap sampling fraction
[labels,~] = unique(data_train(:,end));

% Plot first 4 out of all data subsets
for T = 1:4
    idx = randsample(N,ceil(N*frac),1); % A new training set for each trees is generated by random sampling from dataset WITH replacement.
    prior = histc(data_train(idx,end),labels)/length(idx);
    subplot(2,2,T);
    plot_toydata(data_train(idx,:));
end

%% 2.2 Growing a tree
% Some parameters first
T = 1; % Tree number
param.splitNum = 3; % Number of trials in split function

%% 2.2.1 Node splitting

ig_best = -inf;

for n = 1:param.splitNum
    dim = randi(D-1);                           % Pick one random dimension as a split function
    d_min = single(min(data_train(idx,dim)));   % Find the data range of this dimension
    d_max = single(max(data_train(idx,dim)));
    t = d_min + rand*((d_max-d_min));           % Pick a random value within the range as threshold
       
    idx_ = data_train(idx,dim) < t;             % Split data with this dimension and threshold
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Calculate Information Gain
    
    L = data_train(idx_,:);
    R = data_train(~idx_,:);
    H = getE(data_train);        % Calculate entropy
    HL = getE(L);
    HR = getE(R);
    
    ig = H - sum(idx_)/length(idx_)*HL - sum(~idx_)/length(idx_)*HR
    
    if ig_best < ig
        ig_best = ig;   % maximu information gain saved
        t_best = t;     % the best threhold to save
        dim_best = dim; % the best split function (dimension) to save
        idx_best = idx_;
    end
    
    % Visualise the split function and its information gain
    figure(1)
    visualise_splitfunc(idx_,data_train(idx,:),dim,t,ig,0);
    drawnow;
    disp('Press any key to continue');
    pause; 
end
% Visualise the best split function saved
visualise_splitfunc(idx_best,data_train(idx,:),dim_best,t_best,ig_best,0);

%% 2.2.2 Growing the rest of the tree
% Let's set some parameters...
param.depth = 5;        % Tree depth
param.split = 'IG';     % Currently support 'information gain' only% 

% Initialise base node
trees(T).node(1) = struct('idx',idx,'t',nan,'dim',-1,'prob',[]);
% Split the nodes recursively
for n = 1:2^(param.depth-1)-1
    [trees(T).node(n),trees(T).node(n*2),trees(T).node(n*2+1)] = splitNode(data_train,trees(T).node(n),param);
end

%% 2.2.3 Leaf nodes
% Store class distributions in the leaf nodes
makeLeaf;
% Visualise the class distributions of the first 9 leaf nodes
visualise_leaf;

%% 2.3 Train a random forest
close all;

param.num = 50;         % Number of trees
param.depth = 6;        % Depth of each tree
param.splitNum = 10;     % Number of trials in split function
param.split = 'IG';     % Currently support 'information gain' only

trees = growTrees(data_train,param);

%% 3. Inference (test) in random forest

test_point = [-.5 -.7; .4 .3; -.7 .4; .5 -.5];
figure(1)
plot_toydata(data_train);
plot(test_point(:,1), test_point(:,2), 's', 'MarkerSize',20, 'MarkerFaceColor', [.9 .9 .9], 'MarkerEdgeColor','k');

for n=1:4
    figure(2)
    subplot(1,2,1)
    plot_toydata(data_train);
    subplot(1,2,2)
    leaves = testTrees([test_point(n,:) 0],trees);
    
    % average the class distributions of leaf nodes of all trees
    p_rf = trees(1).prob(leaves,:);
    p_rf_sum = sum(p_rf)/length(trees)
    
    % visualise the class distributions of the leaf nodes which the data
    % point arrives at (for the first 10 trees)
    for L = 1:10
        subplot(3,5,L); bar(p_rf(L,:)); axis([0.5 3.5 0 1]);
    end
    subplot(3,5,L+3); bar(p_rf_sum); axis([0.5 3.5 0 1]);
    
    figure(1);
    hold on;
    plot(test_point(n,1), test_point(n,2), 's', 'MarkerSize',20, 'MarkerFaceColor', p_rf_sum, 'MarkerEdgeColor','k');
    pause;
end
hold off;
close all;

% Let's test the RF on our test data

leaves = testTrees_fast(data_test,trees);

for T = 1:length(trees)
    p_rf_all(:,:,T) = trees(1).prob(leaves(:,T),:);
end

p_rf_all = squeeze(sum(p_rf_all,3))/length(trees);

% Let's visualise the results...
visualise(data_train,p_rf_all,[],0);

%% 4. Random forest parameters
%% 4.1 Number of trees

init ;

for N = [1,3,5,10,20] % Number of trees, try {1,3,5,10, or 20}
    param.num = N;
    param.depth = 5;    % trees depth
    param.splitNum = 10; % Number of trials in split function
    param.split = 'IG'; % Currently support 'information gain' only
  

    % Select dataset
    [data_train, data_test] = getData('Toy_Spiral'); % {'Toy_Gaussian', 'Toy_Spiral', 'Toy_Circle', 'Caltech'}
    
    % Train Random Forest
    trees = growTrees(data_train, param);
    
    % Test Random Forest
    testTrees_script;
    
    % Visualise
    visualise(data_train,p_rf,[],0);
    disp('Press any key to continue');
    pause;
end
%% 4.2 Depth of trees

init;
for N = [2,5,7,11] % Tree depth, try {2,5,7,11}
    param.num = 10;
    param.depth = N;    % trees depth
    param.splitNum = 10; % Number of trials in split function
    param.split = 'IG'; % Currently support 'information gain' only

    % Select dataset
    [data_train, data_test] = getData('Toy_Spiral'); % {'Toy_Gaussian', 'Toy_Spiral', 'Toy_Circle', 'Caltech'}
    
    % Train Random Forest
    trees = growTrees(data_train,param);
    
    % Test Random Forest
    testTrees_script;
    
    % Visualise
    visualise(data_train,p_rf,[],0);
    disp('Press any key to continue');
    pause;
end
%}
%% 5. Experiment with Caltech dataset for image categorisation (Coursework 2)
clear all;
param.num = 10;     % number of trees
param.depth = 10;    % trees depth
param.splitNum = 3; % Number of trials in split function
param.split = 'IG'; % Currently support 'information gain' only

% Complete getData.m by writing your own lines of code to obtain the visual 
% vocabulary and the bag-of-words histograms for both training and testing data. 
% You can use any existing code for K-means (note different codes require different memory and computation time).

[data_train, data_test,test_img_idx, numB,numT,depth,split] = getData_RF('Caltech');

%% 
close all;

param.num = 10;     % number of trees
param.depth = 10;    % trees depth
param.splitNum = 3; % Number of trials in split function
% histogram 출력

figure;
bar(data_train(1,:));
title('Histogram');
xlabel('Values');
ylabel('Frequency');

%pic_name = sprintf('./experiments/q3/codebook/train_histogram_%d_%d_%d.png',numT,depth,split);
pic_name = sprintf('./experiments/q3/classifier/weak_train_histogram_%d_%d_%d.png',param.num, param.depth, param.splitNum);
saveas(gcf, pic_name);

figure;
bar(data_test(1,:));
title('Histogram');
xlabel('Values');
ylabel('Frequency');

pic_name = sprintf('./experiments/q3/classifier/weak_test_histogram_%d_%d_%d.png',param.num, param.depth, param.splitNum);
%pic_name = sprintf('./experiments/q3/classifier/test_histogram_%d_%d_%d.png',param.num, param.depth, param.splitNum);
%pic_name = sprintf('./experiments/q2/wetest_histogram_%d_%d_%d.png', param.num, param.depth, param.splitNum);
saveas(gcf, pic_name);

% Train your random forest with the BoW histograms.
tic
trees = growTrees(data_train,param);
toc

% Test the random forest
tic
testTrees_script;
toc

% Show the results.
confus_script;

% success/failure image 확인
class = 2;
disp("예측 한 class");
disp(c(1+10*(class-1):1+10*class));
disp("img idx");
disp(test_img_idx{class});